version: '3.9'
services:
  application:
    image: '149613315390.dkr.ecr.us-west-2.amazonaws.com/progressforum:a85c54e2'
    ports:
      - "80:3000"
    environment:
      - "MONGO_URL=secrets.MONGO_URL"
