version: '3.9'
services:
  application:
    image: '149613315390.dkr.ecr.us-west-2.amazonaws.com/progressforum:5e719765'
    ports:
      - "80:3000"
    environment:
      - "MONGO_URL=secrets.MONGO_URL"
      - "SMTP_USER=secrets.SMTP_USER"
      - "SMTP_PASSWORD=secrets.SMTP_PASSWORD"
