name: deploy-progress-forum
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ">=3.5"

      - run: pip3 install --upgrade pip awsebcli

      - name: Substitute placeholder environment variables with repository-configured values
        run: sed -i.bak "s|secrets\.MONGO_URL|${{ secrets.MONGO_URL }}|" docker-compose.yml
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}

      - name: Include the modified docker-compose.yml in the to-be-deployed changes
        run: |
          git config --global user.name github_action
          git config --global user.email github_action@github.com
          git add docker-compose.yml

      - name: Execute deployment
        run: eb deploy --verbose --staged --timeout 20
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
